### ISSUE TITLE
Undefined symbol: type metadata for CapacitorCommunitySqlite.JsonView

### ISSUE THREAD

**Issue by t4tapas** [capacitor-community/sqlite#173]
**Describe the bug**
After upgrading to version 3.2.2 from 3.2.0, I am getting the following error while building the IOS app in Xcode

```
Undefined symbols for architecture arm64:
  "type metadata for CapacitorCommunitySqlite.JsonView", referenced from:
      CapacitorCommunitySqlite.Database.importFromJson(jsonSQLite: CapacitorCommunitySqlite.JsonSQLite) throws -> [Swift.String : Swift.Int] in Database.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- OS: [IOS]

**EDIT**
I am on Capacitor 3.2.3 and plugin version 3.2.0 does not have this error.

**Comment by jepiqueau** [comment]
@t4tapas thanks for using the plug-in after updating to 3.2.2 did you remove the iOS folder from your app and after npm run build do npx cap add ios and after npx cap copy. Tell me if after having done this you still have the error. Which framework are you using?

**Comment by t4tapas** [comment]
@jepiqueau , I am using Ionic 5 with Angular. I will do the removing the iOS folder test and let you know.

**Comment by jepiqueau** [comment]
@t4tapas Any news, i updated `https://github.com/jepiqueau/angular-sqlite-app-starter` to @capacitor/core@3.2.2 as well as @capacitor/android, @capacitor/ios and @capacitor-community/sqlite@3.2.2 and i do not have any building issues.

**Comment by jepiqueau** [comment]
@t4tapas Any progress on your side. if no news from you i will close the issue

**Comment by jepiqueau** [comment]
@t4tapas Not having news from you, i assume it is solved so i close the issue. Feel free to re-opens it in case
